#for tts service
- platform: mpd
  host: 192.168.50.111
  port: 6600
  name: mpd

- platform: mpd
  host: 192.168.50.69
  port: 6600
  name: mpd_birdfeed

- platform: snapcast
  host: 192.168.50.111
  port: 1705

#- platform: tts_bluetooth_speaker
#  address: CC:B1:1A:2D:66:18.a2dp_sink
#  volume: 0.45
# Optional - default is 0.5
#  pre_silence_duration: 1
# Optional - No. of seconds silence before the TTS (default is 0)
#  post_silence_duration: 0.5
# Optional - No. of seconds silence after the TTS (default is 0)
#  cache_dir: /tmp/tts
# Optional - make sure it matches the same setting in TTS config
